### ISSUE TITLE
can we have custom commit statuses to link back to the run step?

### ISSUE THREAD

**Issue by aaf-terraform** [ausaccessfed/workflows#565]
https://github.com/ausaccessfed/workflows/blob/42017281bd02dac249586ca95be54f3a38540056/.github/workflows/deploy-sync.yml#L449-L450

```yaml

      DOCKLE_HOST: 'unix:///var/run/docker.sock'
    name: Image scans
    # TODO: can we have custom commit statuses to link back to the run step?
    # Issue URL: https://github.com/ausaccessfed/workflows/issues/565
    steps:
      - uses: ausaccessfed/workflows/.github/actions/image_scanner@main
        name: 'Trivy Repo Scan'

```
